languageCode = "en-gb"
title = "Rootkey"
baseurl = "https://rootkey.netlify.com/"
theme = "darksimplicity"
min_version = 0.45
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
canonifyurls = true

[params]
description = "Life Inside a Computer"
copyright = "&copy Copyright 2017, 2018. Matt Rhone and Dark Simplicity."

[taxonomies]
tag = "tags"

[menu]
  [[menu.top]]
  [[menu.top]]
  name = "RSS"
  pre = ""
  weight = -90
  url = "index.xml"
