languageCode = "en-gb"
title = "Rootkey"
baseurl = "https://rootkey.netlify.com/"
theme = "darksimplicity"
min_version = 0.45
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
canonifyurls = true

[params]
author = "Ciaran Ainsworth"
description = "Life Inside a Computer"
copyright = "&copy Copyright 2017, 2018. Ciaran Ainsworth."

[taxonomies]
tag = "tags"

[menu]
 [[menu.top]]
  name = "Blog"
  pre = ""
  weight = -90
  url = "blog"
 [[menu.top]]
  name = "RSS"
  pre = ""
  weight = -90
  url = "index.xml"
